require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AvailabilitiesController do

  # This should return the minimal set of attributes required to create a valid
  # Availabilitie. As you add validations to Availabilitie, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all availabilities as @availabilities" do
      availabilitie = Availabilitie.create! valid_attributes
      get :index
      assigns(:availabilities).should eq([availabilitie])
    end
  end

  describe "GET show" do
    it "assigns the requested availabilitie as @availabilitie" do
      availabilitie = Availabilitie.create! valid_attributes
      get :show, :id => availabilitie.id.to_s
      assigns(:availabilitie).should eq(availabilitie)
    end
  end

  describe "GET new" do
    it "assigns a new availabilitie as @availabilitie" do
      get :new
      assigns(:availabilitie).should be_a_new(Availabilitie)
    end
  end

  describe "GET edit" do
    it "assigns the requested availabilitie as @availabilitie" do
      availabilitie = Availabilitie.create! valid_attributes
      get :edit, :id => availabilitie.id.to_s
      assigns(:availabilitie).should eq(availabilitie)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Availabilitie" do
        expect {
          post :create, :availabilitie => valid_attributes
        }.to change(Availabilitie, :count).by(1)
      end

      it "assigns a newly created availabilitie as @availabilitie" do
        post :create, :availabilitie => valid_attributes
        assigns(:availabilitie).should be_a(Availabilitie)
        assigns(:availabilitie).should be_persisted
      end

      it "redirects to the created availabilitie" do
        post :create, :availabilitie => valid_attributes
        response.should redirect_to(Availabilitie.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved availabilitie as @availabilitie" do
        # Trigger the behavior that occurs when invalid params are submitted
        Availabilitie.any_instance.stub(:save).and_return(false)
        post :create, :availabilitie => {}
        assigns(:availabilitie).should be_a_new(Availabilitie)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Availabilitie.any_instance.stub(:save).and_return(false)
        post :create, :availabilitie => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested availabilitie" do
        availabilitie = Availabilitie.create! valid_attributes
        # Assuming there are no other availabilities in the database, this
        # specifies that the Availabilitie created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Availabilitie.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => availabilitie.id, :availabilitie => {'these' => 'params'}
      end

      it "assigns the requested availabilitie as @availabilitie" do
        availabilitie = Availabilitie.create! valid_attributes
        put :update, :id => availabilitie.id, :availabilitie => valid_attributes
        assigns(:availabilitie).should eq(availabilitie)
      end

      it "redirects to the availabilitie" do
        availabilitie = Availabilitie.create! valid_attributes
        put :update, :id => availabilitie.id, :availabilitie => valid_attributes
        response.should redirect_to(availabilitie)
      end
    end

    describe "with invalid params" do
      it "assigns the availabilitie as @availabilitie" do
        availabilitie = Availabilitie.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Availabilitie.any_instance.stub(:save).and_return(false)
        put :update, :id => availabilitie.id.to_s, :availabilitie => {}
        assigns(:availabilitie).should eq(availabilitie)
      end

      it "re-renders the 'edit' template" do
        availabilitie = Availabilitie.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Availabilitie.any_instance.stub(:save).and_return(false)
        put :update, :id => availabilitie.id.to_s, :availabilitie => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested availabilitie" do
      availabilitie = Availabilitie.create! valid_attributes
      expect {
        delete :destroy, :id => availabilitie.id.to_s
      }.to change(Availabilitie, :count).by(-1)
    end

    it "redirects to the availabilities list" do
      availabilitie = Availabilitie.create! valid_attributes
      delete :destroy, :id => availabilitie.id.to_s
      response.should redirect_to(availabilities_url)
    end
  end

end
